- name: Deploy Infra | Process Templates
  template: 
    src: "{{ item }}"
    dest: "{{ item_ans_tf_services.terraform_projectpath}}/{{item | basename | regex_replace('.j2','') }}"
  with_fileglob:
    - "{{ item_ans_tf_services.terraform_projectpath }}/templates/*.j2"
  delegate_to: localhost

- name: Deploy Infra | Terraform Init
  command: terraform init
          -input=false
          -reconfigure
          -force-copy
          {{ item_ans_tf_services.terraform_projectpath }}
  register: result
  failed_when: result.rc != 0
  changed_when: "result.rc == 0"
  delegate_to: localhost

- name: Deploy Infra | Display Output
  debug: var=result

- name: Deploy Infra | Terraform Validate
  command: terraform validate 
          {{ item_ans_tf_services.terraform_projectpath }}
  register: result
  failed_when: result.rc != 0
  changed_when: "result.rc == 0"
  delegate_to: localhost

- name: Deploy Infra | Display Output
  debug: var=result

- name: Deploy Infra | Terraform Build Destroy Plan
  command: terraform plan
        -detailed-exitcode
        -input=false
        -out="{{ item_ans_tf_services.terraform_planname }}"
        -destroy
        {{ item_ans_tf_services.terraform_projectpath }}
  register: result
  failed_when: result.rc == 1
  changed_when: "result.rc == 2"
  delegate_to: localhost
  when: item_ans_tf_services.destroy

- name: Deploy Infra | Terraform Build Apply Plan
  command: terraform plan
        -detailed-exitcode
        -input=false
        -out="{{ item_ans_tf_services.terraform_planname }}"
        {{ item_ans_tf_services.terraform_projectpath }}
  register: result
  failed_when: result.rc == 1
  changed_when: "result.rc == 2"
  delegate_to: localhost
  when: not item_ans_tf_services.destroy

- name: Deploy Infra | Display Output
  debug: var=result

- name: Deploy Infra | Terraform Apply
  command: terraform apply
        -auto-approve
        -input=false
        "{{ item_ans_tf_services.terraform_planname }}"
  register: result
  failed_when: result.rc != 0
  changed_when: "result.rc == 0"
  delegate_to: localhost

- name: Deploy Infra | Display Output
  debug: var=result
